"""
Laminar - Notification Service
------------------------------

Handles real email notifications for Crowd Alerts.

Responsibilities:
- Send colored HTML emails
- Route to management / police / supervisors
- Respect cooldown window
- Update last_notified_at
- Include camera & venue location
- Production-safe async SMTP
"""

from typing import List
from uuid import UUID
from datetime import datetime, timezone

import aiosmtplib
from email.message import EmailMessage

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.crowd_alert import CrowdAlert
from app.models.camera import Camera
from app.models.venue import Venue
from app.core.repository import Repository
from app.core.logging import get_logger


logger = get_logger(__name__)


class NotificationService:
    """
    Production-ready email notification engine.
    """

    COLOR_MAP = {
        "low": "#16a34a",       # green
        "medium": "#eab308",    # yellow
        "high": "#f97316",      # orange
        "critical": "#dc2626",  # red
    }

    async def notify(
        self,
        session: AsyncSession,
        alert: CrowdAlert,
    ) -> None:
        """
        Send notification for alert if cooldown allows.
        """

        # Cooldown protection
        if alert.last_notified_at:
            diff = datetime.now(timezone.utc) - alert.last_notified_at
            if diff.total_seconds() < 300:  # 5 minutes
                logger.info(
                    "Notification skipped due to cooldown",
                    extra={"alert_id": str(alert.id)},
                )
                return

        venue_repo = Repository[Venue](Venue)
        camera_repo = Repository[Camera](Camera)

        venue = await venue_repo.get_by_id(session, alert.venue_id)
        camera = None

        if alert.metric_id:
            # Optional camera resolution (if metric linked)
            # You can extend metric → camera mapping later if needed
            pass

        color = self.COLOR_MAP.get(alert.risk_level, "#16a34a")

        location_text = venue.location or venue.address or venue.name

        if camera:
            location_text = camera.get_display_location()

        recipients = self._resolve_recipients(alert)

        if not recipients:
            logger.warning("No email recipients configured.")
            return

        message = self._build_email(
            alert=alert,
            venue=venue,
            location_text=location_text,
            color=color,
        )

        await self._send_email(message, recipients)

        alert.last_notified_at = datetime.now(timezone.utc)
        await session.commit()

        logger.info(
            "Notification sent",
            extra={
                "alert_id": str(alert.id),
                "risk_level": alert.risk_level,
                "recipients": recipients,
            },
        )

    def _resolve_recipients(self, alert: CrowdAlert) -> List[str]:
        recipients = settings.get_management_emails()

        if alert.risk_level in ["high", "critical"]:
            recipients += settings.get_supervisor_emails()

        if alert.risk_level == "critical":
            recipients += settings.get_police_emails()

        return list(set(recipients))

    def _build_email(
        self,
        alert: CrowdAlert,
        venue: Venue,
        location_text: str,
        color: str,
    ) -> EmailMessage:

        msg = EmailMessage()
        msg["From"] = settings.SMTP_USER
        msg["Subject"] = f"[{alert.risk_level.upper()}] Crowd Alert - {venue.name}"

        msg.set_content("This email requires HTML support.")

        html_content = f"""
        <html>
        <body style="font-family: Arial, sans-serif; margin:0; padding:0;">
            <div style="background:{color}; padding:20px; color:white;">
                <h1 style="margin:0;">Crowd Risk Alert</h1>
                <h2 style="margin:0;">{alert.risk_level.upper()}</h2>
            </div>

            <div style="padding:20px;">
                <p><strong>Venue:</strong> {venue.name}</p>
                <p><strong>Location:</strong> {location_text}</p>
                <p><strong>Status:</strong> {alert.status}</p>
                <p><strong>Severity Score:</strong> {alert.severity}</p>
                <p><strong>Escalation Level:</strong> {alert.escalation_level}</p>
                <p><strong>Time:</strong> {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}</p>

                <hr/>

                <p style="font-size:14px; color:#555;">
                    This is an automated alert generated by Laminar Monitoring System.
                </p>
            </div>
        </body>
        </html>
        """

        msg.add_alternative(html_content, subtype="html")

        return msg

    async def _send_email(
        self,
        message: EmailMessage,
        recipients: List[str],
    ) -> None:

        message["To"] = ", ".join(recipients)

        await aiosmtplib.send(
            message,
            hostname=settings.SMTP_HOST,
            port=settings.SMTP_PORT,
            username=settings.SMTP_USER,
            password=settings.SMTP_PASSWORD,
            start_tls=settings.SMTP_USE_TLS,
        )
