"""
Laminar AI Autonomous Operations Intelligence Engine
=====================================================

This is the central intelligence layer of the Laminar platform.

It reasons about live surveillance data, crowd metrics, prediction outputs,
and multi-camera correlations to generate structured operational intelligence.

Architecture:
  Camera Workers → Vision Inference → Crowd Metrics → Prediction Services
                          ↓
             Laminar AI Intelligence Engine (THIS SERVICE)
                          ↓
         Structured Intelligence Reports → Alert/Notification Pipeline

Outputs follow the format:
  - Situation Analysis
  - Observed Trends
  - Risk Assessment
  - Predicted Outcome
  - Recommended Actions

Intelligence is generated via the AIFallbackProvider (Gemini -> Groq -> Ollama), with
a robust rule-based fallback engine for when the models are offline.
"""

import httpx
import asyncio
import json
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional, Tuple
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc, func, and_

from app.core.logging import get_logger
from app.models.venue import Venue
from app.models.camera import Camera
from app.models.crowd_alert import CrowdAlert
from app.models.crowd_metric import CrowdMetric

logger = get_logger(__name__)

# ─── Constants ────────────────────────────────────────────────────────────────

OLLAMA_BASE = "http://localhost:11434"
# Preferred model order — Focus on Llama 3.2 as primary high-performance model
PREFERRED_MODELS = ["llama3.2", "llama3", "mistral", "phi3"]


class OperationalIntelligence:
    """
    Data class representing a full operational intelligence report.
    
    Every field is populated with meaningful data — never None or empty.
    """
    def __init__(
        self,
        situation_analysis: str,
        observed_trends: str,
        risk_assessment: str,
        predicted_outcome: str,
        recommended_actions: List[str],
        severity: str,
        confidence: str,
        generated_by: str = "rule-based",
        cross_camera_insights: Optional[str] = None,
        timestamp: Optional[str] = None,
    ):
        self.situation_analysis = situation_analysis
        self.observed_trends = observed_trends
        self.risk_assessment = risk_assessment
        self.predicted_outcome = predicted_outcome
        self.recommended_actions = recommended_actions
        self.severity = severity
        self.confidence = confidence
        self.generated_by = generated_by
        self.cross_camera_insights = cross_camera_insights
        self.timestamp = timestamp or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "situation_analysis": self.situation_analysis,
            "observed_trends": self.observed_trends,
            "risk_assessment": self.risk_assessment,
            "predicted_outcome": self.predicted_outcome,
            "recommended_actions": self.recommended_actions,
            "cross_camera_insights": self.cross_camera_insights,
            "severity": self.severity,
            "confidence": self.confidence,
            "generated_by": self.generated_by,
            "timestamp": self.timestamp,
        }

    def to_text(self) -> str:
        """Format intelligence as a clean readable text report."""
        actions = "\n".join(f"  • {a}" for a in self.recommended_actions)
        cross_cam = f"\n\n🎥 CROSS-CAMERA CORRELATION\n{self.cross_camera_insights}" if self.cross_camera_insights else ""
        return (
            f"📡 LAMINAR AI INTELLIGENCE REPORT\n"
            f"Time: {self.timestamp} | Confidence: {self.confidence} | Generated by: {self.generated_by}\n"
            f"{'═' * 60}\n\n"
            f"📍 SITUATION ANALYSIS\n{self.situation_analysis}\n\n"
            f"📊 OBSERVED TRENDS\n{self.observed_trends}\n\n"
            f"⚠️ RISK ASSESSMENT [{self.severity.upper()}]\n{self.risk_assessment}\n\n"
            f"🔮 PREDICTED OUTCOME\n{self.predicted_outcome}\n\n"
            f"🛡️ RECOMMENDED ACTIONS\n{actions}"
            f"{cross_cam}"
        )


class LaminarIntelligenceService:
    """
    Laminar AI Autonomous Operations Intelligence Engine.

    The central intelligence layer that analyzes surveillance data,
    detects emerging risks, correlates multi-camera patterns, and
    generates human-readable operational intelligence reports.
    
    Powered by Llama 3.2 (via Ollama) with a robust rule-based fallback.
    """

    # Class-level model cache
    _cached_model: str = ""
    _ollama_online: bool = False
    _last_probe: Optional[datetime] = None
    PROBE_INTERVAL_SECONDS = 120

    # Cache for insights to prevent repetition
    _insight_cache: Dict[str, Dict[str, Any]] = {}

    def __init__(self):
        pass

    # ─── LLM Detection and Invocation ─────────────────────────────────────────

    async def _detect_model(self) -> str:
        """Returns the current model in use, dummy for backward compatibility."""
        LaminarIntelligenceService._ollama_online = True  # We assume the fallback chain is online
        return "AIFallbackProvider"

    async def _call_llm(self, prompt: str, model: str, timeout: float = 30.0) -> Tuple[Optional[str], str]:
        """Call AI Router and return response text + provider name, or (None, 'None') on failure."""
        try:
            from app.services.ai_service import get_ai_service
            ai_service = get_ai_service()
            res, provider_name = await ai_service.generate_raw(prompt, timeout=timeout, return_provider_name=True)
            return res, provider_name
        except Exception as e:
            logger.debug(f"LLM call failed: {e}")
            return None, "None"

    # ─── Data Gathering ───────────────────────────────────────────────────────

    async def _gather_venue_context(
        self, session: AsyncSession, venue_id: UUID
    ) -> Dict[str, Any]:
        """Gather rich venue context: cameras, metrics, alerts, capacity."""
        context: Dict[str, Any] = {
            "venue": None,
            "cameras": [],
            "recent_metrics": [],
            "active_alerts": [],
            "trend_metrics": [],
        }

        # Venue
        venue_result = await session.execute(
            select(Venue).where(Venue.id == venue_id).limit(1)
        )
        venue = venue_result.scalar_one_or_none()
        if venue:
            context["venue"] = {
                "name": venue.name,
                "capacity": venue.capacity,
                "city": venue.city,
                "type": venue.venue_type,
                "warning_threshold": venue.warning_threshold,
                "critical_threshold": venue.critical_threshold,
                "warning_threshold_pct": venue.warning_threshold_percent,
                "critical_threshold_pct": venue.critical_threshold_percent,
            }

        # Cameras in venue
        cam_result = await session.execute(
            select(Camera).where(Camera.venue_id == venue_id)
        )
        cameras = cam_result.scalars().all()
        context["cameras"] = [
            {
                "id": str(c.id),
                "name": c.name,
                "location": getattr(c, "location_label", None) or getattr(c, "stream_url", ""),
                "status": "active" if (c.is_active and c.is_online) else ("inactive" if not c.is_active else "offline"),
            }
            for c in cameras
        ]

        # Recent crowd metrics (last 10 minutes, per camera)
        ten_min_ago = datetime.now(timezone.utc) - timedelta(minutes=10)
        metrics_result = await session.execute(
            select(CrowdMetric)
            .where(
                CrowdMetric.venue_id == venue_id,
                CrowdMetric.bucket_start >= ten_min_ago,
                CrowdMetric.bucket_type == "minute",
            )
            .order_by(desc(CrowdMetric.bucket_start))
            .limit(30)
        )
        metrics = metrics_result.scalars().all()
        context["recent_metrics"] = [
            {
                "camera_id": str(m.camera_id) if m.camera_id else None,
                "avg_count": float(m.avg_count or 0),
                "max_count": float(m.max_count or 0),
                "risk_level": m.risk_level,
                "bucket_start": m.bucket_start.strftime("%H:%M"),
            }
            for m in metrics
        ]

        # 1-hour trend (hourly buckets)
        one_hr_ago = datetime.now(timezone.utc) - timedelta(hours=1)
        trend_result = await session.execute(
            select(CrowdMetric)
            .where(
                CrowdMetric.venue_id == venue_id,
                CrowdMetric.bucket_start >= one_hr_ago,
                CrowdMetric.bucket_type == "minute",
                CrowdMetric.camera_id.is_(None),
            )
            .order_by(CrowdMetric.bucket_start)
            .limit(60)
        )
        trend_metrics = trend_result.scalars().all()
        context["trend_metrics"] = [
            {"time": m.bucket_start.strftime("%H:%M"), "count": float(m.avg_count or 0), "risk": m.risk_level}
            for m in trend_metrics
        ]

        # Active alerts
        alerts_result = await session.execute(
            select(CrowdAlert)
            .where(CrowdAlert.venue_id == venue_id, CrowdAlert.status.in_(["open", "acknowledged"]))
            .order_by(desc(CrowdAlert.created_at))
            .limit(5)
        )
        alerts = alerts_result.scalars().all()
        context["active_alerts"] = [
            {
                "risk_level": a.risk_level,
                "severity": a.severity,
                "created_at": a.created_at.strftime("%H:%M"),
                "escalation_level": a.escalation_level,
                "predicted_level": a.predicted_level,
                "escalation_probability": a.escalation_probability,
            }
            for a in alerts
        ]

        return context

    async def _gather_multi_camera_context(
        self, session: AsyncSession, venue_id: UUID
    ) -> str:
        """Compute cross-camera statistics for pattern detection."""
        ten_min_ago = datetime.now(timezone.utc) - timedelta(minutes=10)
        
        cam_result = await session.execute(
            select(Camera).where(Camera.venue_id == venue_id, Camera.is_active == True)
        )
        cameras = cam_result.scalars().all()
        
        if not cameras:
            return "No active cameras found for multi-camera analysis."
        
        camera_summaries = []
        high_activity_cams = []
        low_activity_cams = []
        total_count = 0
        
        # Use venue thresholds for activity classification if available
        venue_result = await session.execute(select(Venue).where(Venue.id == venue_id).limit(1))
        venue = venue_result.scalar_one_or_none()
        warn_limit = venue.warning_threshold if venue and venue.warning_threshold else (venue.capacity * 0.7 if venue and venue.capacity else 50.0)
        
        high_threshold = warn_limit * 0.25 # High for a single zone
        low_threshold = warn_limit * 0.05
        
        for cam in cameras:
            m_result = await session.execute(
                select(func.avg(CrowdMetric.avg_count), func.max(CrowdMetric.max_count))
                .where(
                    CrowdMetric.camera_id == cam.id,
                    CrowdMetric.bucket_start >= ten_min_ago,
                )
            )
            row = m_result.first()
            avg_c = float(row[0] or 0) if row else 0
            max_c = float(row[1] or 0) if row else 0
            total_count += avg_c

            cam_name = cam.name or f"Camera {str(cam.id)[:8]}"
            camera_summaries.append(f"  - {cam_name}: avg {avg_c:.0f} persons, peak {max_c:.0f}")

            if avg_c > high_threshold:
                high_activity_cams.append(cam_name)
            elif avg_c < low_threshold:
                low_activity_cams.append(cam_name)

        lines = [f"Active cameras: {len(cameras)}"]
        lines.extend(camera_summaries)
        lines.append(f"Combined crowd load: {total_count:.0f} persons across all cameras")
        
        if high_activity_cams:
            lines.append(f"High-activity zones: {', '.join(high_activity_cams)}")
        if low_activity_cams:
            lines.append(f"Low-activity zones: {', '.join(low_activity_cams)}")
        
        # Bottleneck detection: highlight camera clusters near capacity
        if len(high_activity_cams) >= 2:
            lines.append(
                f"⚡ PATTERN DETECTED: Multiple high-density zones active simultaneously — "
                f"possible crowd convergence or mass movement."
            )

        return "\n".join(lines)

    # ─── Rule-Based Fallback Intelligence ────────────────────────────────────

    def _rule_based_intelligence(
        self, context: Dict[str, Any], cross_camera: str, alert: Optional[CrowdAlert] = None, lang: str = "en"
    ) -> OperationalIntelligence:
        """
        Generate structured intelligence without LLM.
        Always returns a meaningful, factual report based on real data.
        """
        venue = context.get("venue") or {}
        metrics = context.get("recent_metrics", [])
        alerts = context.get("active_alerts", [])
        trends = context.get("trend_metrics", [])
        cameras = context.get("cameras", [])

        venue_name = venue.get("name", "the venue")
        capacity = venue.get("capacity", "N/A")
        risk_score = venue.get("risk_score") or 0

        # Compute averages
        total_avg = sum(m["avg_count"] for m in metrics) / max(len(metrics), 1)
        total_peak = max((m["max_count"] for m in metrics), default=0)
        risk_levels = [m["risk_level"] for m in metrics if m.get("risk_level")]
        dominant_risk = max(set(risk_levels), key=risk_levels.count) if risk_levels else "low"

        # Trend analysis
        if len(trends) >= 3:
            older_avg = sum(t["count"] for t in trends[:max(len(trends)//2, 1)]) / max(len(trends)//2, 1)
            newer_avg = sum(t["count"] for t in trends[len(trends)//2:]) / max(len(trends)//2, 1)
            
            from app.services.translation_service import TranslationService as TS
            t_svc = TS.t

            if newer_avg > older_avg * 1.2:
                pct = ((newer_avg/max(older_avg,1)-1)*100)
                trend_desc = t_svc(lang, "intel_trend_upward", 
                    "Crowd count is trending upward — recent average ({newer:.0f}) exceeds earlier average ({older:.0f}) by {pct:.0f}%."
                ).format(newer=newer_avg, older=older_avg, pct=pct)
            elif newer_avg < older_avg * 0.8:
                trend_desc = t_svc(lang, "intel_trend_downward", 
                    "Crowd count is declining — recent average ({newer:.0f}) is lower than earlier average ({older:.0f})."
                ).format(newer=newer_avg, older=older_avg)
            else:
                trend_desc = t_svc(lang, "intel_trend_stable", 
                    "Crowd count is stable around {count:.0f} persons."
                ).format(count=newer_avg)
        else:
            from app.services.translation_service import TranslationService as TS
            t_svc = TS.t
            trend_desc = t_svc(lang, "intel_trend_insufficient", 
                "Current crowd average: {avg:.0f} persons (peak: {peak:.0f})."
            ).format(avg=total_avg, peak=total_peak)

        # Alert prediction context
        predicted_level = None
        esc_prob = 0.0
        if alerts:
            top_alert = alerts[0]
            predicted_level = top_alert.get("predicted_level")
            esc_prob = top_alert.get("escalation_probability") or 0.0

        # Severity
        severity_map = {"critical": "CRITICAL", "high": "HIGH", "medium": "MEDIUM", "low": "LOW"}
        alert_risk = alert.risk_level if alert else dominant_risk
        severity = severity_map.get(alert_risk, "MODERATE")

        from app.services.translation_service import TranslationService
        t = TranslationService.t
        
        situation = t(lang, "intel_situation", 
            "Surveillance intelligence identified a {severity} crowd condition at {venue_name}. "
            "The venue capacity is {capacity} persons. "
            "Real-time monitoring across {cam_count} active camera(s) "
            "shows a current crowd average of {avg:.0f} with a peak of {peak:.0f} persons."
        ).format(
            severity=severity, venue_name=venue_name, capacity=capacity, 
            cam_count=len(cameras), avg=total_avg, peak=total_peak
        )

        observed = t(lang, "intel_observed",
            "{trend_desc} "
            "Risk scoring across sensor feeds indicates a dominant risk classification of {risk}. "
            "Dynamic risk score: {score:.2f}."
        ).format(
            trend_desc=trend_desc, risk=dominant_risk.upper(), score=float(risk_score or 0)
        )

        risk_text = t(lang, "intel_risk", 
            "{alert_info}Current crowd conditions at {venue_name} are classified as {severity}. "
        ).format(
            alert_info=(t(lang, "active_alert_note", "Active alert is in effect. ") if alerts else ""),
            venue_name=venue_name, severity=severity
        )
        
        if predicted_level and esc_prob > 0:
            risk_text += t(lang, "intel_prediction_addon", 
                "The prediction engine projects escalation to {level} with a probability of {prob}%."
            ).format(level=predicted_level.upper(), prob=int(esc_prob * 100))
            
        if alert and alert.escalation_level > 0:
            risk_text += " " + t(lang, "intel_esc_note", "Escalation level {level} has been triggered.").format(level=alert.escalation_level)

        if predicted_level and esc_prob > 0.5:
            prediction = t(lang, "intel_outcome_high",
                "High probability ({prob}%) of crowd conditions escalating to {level}. "
                "If current movement patterns persist, venue saturation may occur within the next 10-20 minutes."
            ).format(prob=int(esc_prob*100), level=predicted_level.upper())
        elif dominant_risk in ["high", "critical"]:
            prediction = t(lang, "intel_outcome_elevated",
                "Crowd dynamics suggest sustained high-risk conditions. If inflow continues at current rate, "
                "critical thresholds may be reached within the next 15-30 minutes."
            )
        else:
            prediction = t(lang, "intel_outcome_nominal",
                "Based on current patterns, crowd levels are expected to remain at {risk} risk for the near term. Continue standard monitoring protocols."
            ).format(risk=dominant_risk.upper())

        # Generate specific actions
        actions = []
        if alert_risk == "critical":
            actions = [
                t(lang, "action_critical_1", "IMMEDIATE: Deploy full security response and crowd safety team to {venue}.").format(venue=venue_name),
                t(lang, "action_critical_2", "Issue public announcement to redirect crowd flow toward less congested exits."),
                t(lang, "action_critical_3", "Notify emergency services and establish incident command if not already active."),
                t(lang, "action_critical_4", "Freeze new entry at all access gates until crowd density normalizes."),
                t(lang, "action_critical_5", "Coordinate contingency staff for evacuation route management."),
            ]
        elif alert_risk == "high":
            actions = [
                t(lang, "action_high_1", "Alert supervisors and activate crowd-control protocols at {venue}.").format(venue=venue_name),
                t(lang, "action_high_2", "Deploy additional staff to high-density zones identified by camera feeds."),
                t(lang, "action_high_3", "Consider opening additional gates or exit pathways to distribute crowd load."),
                t(lang, "action_high_4", "Issue advisory announcements guiding visitors to alternate zones."),
            ]
        elif alert_risk == "medium":
            actions = [
                t(lang, "action_medium_1", "Monitor all camera feeds at elevated frequency."),
                t(lang, "action_medium_2", "Pre-position contingency staff near high-density zones."),
                t(lang, "action_medium_3", "Prepare crowd-control equipment and communications for rapid deployment."),
            ]
        else:
            actions = [
                t(lang, "action_low_1", "Continue standard monitoring and periodic safety sweeps."),
                t(lang, "action_low_2", "Ensure all camera feeds are operational and reporting."),
                t(lang, "action_low_3", "Log current crowd distribution for historical pattern analysis."),
            ]

        confidence = t(lang, "moderate", "moderate") if not metrics else t(lang, "high", "high")
        
        return OperationalIntelligence(
            situation_analysis=situation,
            observed_trends=observed,
            risk_assessment=risk_text,
            predicted_outcome=prediction,
            recommended_actions=actions,
            severity=severity,
            confidence=confidence,
            generated_by=t(lang, "intel_engine_name", "Laminar Rule-Based Intelligence Engine"),
            cross_camera_insights=cross_camera if cross_camera else None,
        )

    # ─── LLM-Powered Intelligence ─────────────────────────────────────────────

    async def _llm_intelligence(
        self, model: str, context: Dict[str, Any], cross_camera: str, alert: Optional[CrowdAlert] = None, prev_intel: Optional[OperationalIntelligence] = None, lang: str = "en"
    ) -> Optional[OperationalIntelligence]:
        """
        Use Llama 3.2 to generate full structured operational intelligence.
        Returns None if LLM fails (fallback to rule-based).
        """
        venue = context.get("venue") or {}
        metrics = context.get("recent_metrics", [])
        alerts_ctx = context.get("active_alerts", [])
        trends = context.get("trend_metrics", [])
        cameras = context.get("cameras", [])

        # Build a rich, concise data snapshot for the LLM
        venue_str = json.dumps(venue, indent=2)
        metrics_str = json.dumps(metrics[:8], indent=2)  # Limit to avoid token overflow
        alerts_str = json.dumps(alerts_ctx[:3], indent=2)
        trend_str = json.dumps(trends[-12:], indent=2) if trends else "[]"
        alert_risk = alert.risk_level.upper() if alert else "UNKNOWN"
        alert_predicted = getattr(alert, "predicted_level", "UNKNOWN") or "UNKNOWN"
        alert_esc_prob = getattr(alert, "escalation_probability", 0) or 0.0

        prompt = f"""You are the Laminar AI Autonomous Operations Intelligence Engine.

You are an expert crowd operations analyst embedded in the Laminar AI Crowd Intelligence platform.

Your task: Analyze the provided surveillance intelligence and produce a structured operational intelligence report.

CURRENT ALERT:
- Risk Level: {alert_risk}
- Predicted Escalation Level: {alert_predicted.upper()}
- Escalation Probability: {int(alert_esc_prob * 100)}%

VENUE DATA:
{venue_str}

ACTIVE CAMERAS ({len(cameras)} cameras):
{json.dumps([c['name'] for c in cameras[:10]], indent=2)}

CROSS-CAMERA ANALYSIS:
{cross_camera}

RECENT CROWD METRICS (last 10 minutes):
{metrics_str}

HOURLY TREND (last 60 minutes):
{trend_str}

ACTIVE ALERTS:
{alerts_str}
"""
        if prev_intel:
            prompt += f"\nPREVIOUS INSIGHT (For context, DO NOT repeat these exact phrases, provide an update):\n- Situation: {prev_intel.situation_analysis}\n- Predicted: {prev_intel.predicted_outcome}\n"

        prompt += """
Reason about patterns: crowd accumulation, convergence points, movement vectors, zone imbalances.
Do NOT use generic statements. Use specific data points.

LANGUAGE INSTRUCTION: Please generate your response entirely in English. It will be natively translated downstream.

Produce a JSON response with these exact fields:
{{
  "situation_analysis": "2-3 sentences describing the current situation based on data",
  "observed_trends": "2-3 sentences describing detected patterns across cameras and metrics",
  "risk_assessment": "2-3 sentences evaluating the risk with specific reasoning",
  "predicted_outcome": "2-3 sentences with probabilistic prediction of near-term crowd state",
  "recommended_actions": ["action 1", "action 2", "action 3", "action 4"],
  "severity": "critical|high|medium|low",
  "confidence": "high|moderate|low"
}}

Respond ONLY with valid JSON. No preamble, no explanation.
"""

        raw, actual_model_name = await self._call_llm(prompt, model, timeout=35.0)
        if not raw:
            return None

        # Extract JSON block from response
        try:
            # Find first { and last }
            start = raw.find("{")
            end = raw.rfind("}") + 1
            if start == -1 or end == 0:
                return None
            data = json.loads(raw[start:end])
            
            # Post-process for perfect Native Script if not English
            if lang != "en":
                try:
                    from deep_translator import GoogleTranslator
                    translator = GoogleTranslator(source='en', target=lang)
                    
                    data["situation_analysis"] = translator.translate(data.get("situation_analysis", ""))
                    data["observed_trends"] = translator.translate(data.get("observed_trends", ""))
                    data["risk_assessment"] = translator.translate(data.get("risk_assessment", ""))
                    data["predicted_outcome"] = translator.translate(data.get("predicted_outcome", ""))
                    data["recommended_actions"] = [translator.translate(a) for a in data.get("recommended_actions", [])]
                    
                    if cross_camera:
                        cross_camera = translator.translate(cross_camera)
                except Exception as e:
                    logger.error(f"Translation failed: {e}")

            return OperationalIntelligence(
                situation_analysis=data.get("situation_analysis", ""),
                observed_trends=data.get("observed_trends", ""),
                risk_assessment=data.get("risk_assessment", ""),
                predicted_outcome=data.get("predicted_outcome", ""),
                recommended_actions=data.get("recommended_actions", []),
                severity=data.get("severity", alert_risk),
                confidence=data.get("confidence", "moderate"),
                generated_by=f"Laminar AI ({actual_model_name})",
                cross_camera_insights=cross_camera,
            )
        except Exception as e:
            logger.warning(f"LLM response JSON parse failed: {e}. Raw: {raw[:200]}")
            return None

    # ─── Main Public API ──────────────────────────────────────────────────────

    async def analyze_venue(
        self, session: AsyncSession, venue_id: UUID, alert: Optional[CrowdAlert] = None, lang: str = "en"
    ) -> OperationalIntelligence:
        """
        Main entry point — generate full operational intelligence for a venue.
        
        Attempts Llama 3.2 first; falls back to rule-based engine.
        
        Args:
            session: DB session
            venue_id: Venue to analyze
            alert: Optional triggering alert for context
        
        Returns:
            OperationalIntelligence with full structured report
        """
        # Gather all real data
        context = await self._gather_venue_context(session, venue_id)
        cross_camera = await self._gather_multi_camera_context(session, venue_id)

        # ==========================================================
        # AI OUTPUT STABILITY (MODULE 6) - Caching & Anti-Repetition
        # ==========================================================
        venue_key = str(venue_id)
        now = datetime.now(timezone.utc)
        
        metrics = context.get("recent_metrics", [])
        total_avg = sum(m["avg_count"] for m in metrics) / max(len(metrics), 1) if metrics else 0
        alerts = context.get("active_alerts", [])
        alert_count = len(alerts)
        
        cached = self._insight_cache.get(venue_key)
        if cached:
            age_secs = (now - cached["timestamp"]).total_seconds()
            
            # 1) If less than 2 minutes old, always return cache to prevent spam
            if age_secs < 120:
                logger.debug(f"Returning heavily cached intelligence for venue {venue_id} (age {int(age_secs)}s)")
                return cached["intel"]
                
            # 2) If less than 10 minutes old AND state hasn't changed much, return cache
            if age_secs < 600 and cached["alert_count"] == alert_count:
                if abs(cached["total_avg"] - total_avg) < max(10.0, cached["total_avg"] * 0.15):
                    logger.debug(f"Returning cached intelligence (stable state) for venue {venue_id} (age {int(age_secs)}s)")
                    return cached["intel"]

        prev_intel = cached["intel"] if cached else None

        # Try LLM first
        model = await self._detect_model()
        final_intel = None
        if model:
            try:
                intel = await asyncio.wait_for(
                    self._llm_intelligence(model, context, cross_camera, alert, prev_intel, lang=lang),
                    timeout=40.0
                )
                if intel and intel.situation_analysis:
                    logger.info(f"LLM intelligence generated for venue {venue_id} using {model}")
                    final_intel = intel
            except asyncio.TimeoutError:
                logger.warning("LLM intelligence generation timed out — using rule-based fallback")
            except Exception as e:
                logger.warning(f"LLM intelligence failed: {e} — using rule-based fallback")

        # Fallback to rule-based engine
        if not final_intel:
            logger.info(f"Generating rule-based intelligence for venue {venue_id}")
            final_intel = self._rule_based_intelligence(context, cross_camera, alert, lang=lang)

        # Update cache
        self._insight_cache[venue_key] = {
            "timestamp": now,
            "intel": final_intel,
            "total_avg": total_avg,
            "alert_count": alert_count,
        }

        return final_intel

    async def generate_notification_brief(
        self, session: AsyncSession, alert: CrowdAlert, venue_name: str, location: str, lang: str = "en"
    ) -> str:
        """
        Generate a concise AI intelligence brief for notifications/emails.
        
        This replaces the simpler `_generate_ai_brief` in notification_service
        with the full intelligence engine output.
        
        Returns a pre-formatted text suitable for inclusion in email notifications.
        """
        try:
            intel = await self.analyze_venue(session, alert.venue_id, alert, lang=lang)
            
            from app.services.translation_service import TranslationService
            t = TranslationService.t
            
            # Format as a clean email-friendly brief
            actions_text = "\n".join(f"  • {a}" for a in intel.recommended_actions[:3])
            
            # Localized headers
            h_assessment = t(lang, "intel_assessment_header", "LAMINAR AI INTELLIGENCE ASSESSMENT")
            h_situation = t(lang, "intel_situation_header", "SITUATION")
            h_trends = t(lang, "intel_trend_header", "TREND ANALYSIS")
            h_risk = t(lang, "intel_risk_header", "RISK ASSESSMENT")
            h_outcome = t(lang, "intel_outcome_header", "PREDICTED OUTCOME")
            h_actions = t(lang, "intel_actions_header", "IMMEDIATE ACTIONS REQUIRED")
            h_correlation = t(lang, "intel_correlation_header", "MULTI-CAMERA CORRELATION")
            h_gen_by = t(lang, "generated_by_label", "Generated by")

            brief = (
                f"═══ {h_assessment} ═══\n\n"
                f"📍 {h_situation}\n{intel.situation_analysis}\n\n"
                f"📊 {h_trends}\n{intel.observed_trends}\n\n"
                f"⚠️ {h_risk} [{intel.severity}]\n{intel.risk_assessment}\n\n"
                f"🔮 {h_outcome}\n{intel.predicted_outcome}\n\n"
                f"🛡️ {h_actions}\n{actions_text}\n"
            )
            if intel.cross_camera_insights:
                brief += f"\n🎥 {h_correlation}\n{intel.cross_camera_insights}\n"
            
            brief += f"\n_{h_gen_by}: {intel.generated_by} | {intel.timestamp}_"
            return brief
        except Exception as e:
            logger.error(f"Intelligence brief generation failed: {e}")
            return (
                f"Crowd intelligence alert for {venue_name} at {location}. "
                f"Risk level: {alert.risk_level.upper()}. Please review the dashboard for full details."
            )

    async def get_system_intelligence(self, session: AsyncSession) -> Dict[str, Any]:
        """
        Generate a system-wide intelligence overview across all venues.
        
        Used for the API endpoint to provide a real-time intelligence dashboard.
        """
        # Gather all venues
        venues_result = await session.execute(select(Venue).where(Venue.is_active == True))
        venues = venues_result.scalars().all()

        # Active alerts summary
        alerts_result = await session.execute(
            select(CrowdAlert)
            .where(CrowdAlert.status.in_(["open", "acknowledged"]))
            .order_by(desc(CrowdAlert.severity))
            .limit(10)
        )
        alerts = alerts_result.scalars().all()

        # Latest crowd metrics (last 5 minutes per venue)
        five_min_ago = datetime.now(timezone.utc) - timedelta(minutes=5)
        metrics_result = await session.execute(
            select(CrowdMetric)
            .where(
                CrowdMetric.bucket_start >= five_min_ago,
                CrowdMetric.bucket_type == "minute",
                CrowdMetric.camera_id.is_(None),
            )
            .order_by(desc(CrowdMetric.avg_count))
            .limit(20)
        )
        metrics = metrics_result.scalars().all()

        # Compute system-wide stats
        total_crowd = sum(float(m.avg_count or 0) for m in metrics)
        risk_levels = [a.risk_level for a in alerts]
        critical_count = risk_levels.count("critical")
        high_count = risk_levels.count("high")

        system_status = "nominal"
        if critical_count > 0:
            system_status = "critical"
        elif high_count > 0:
            system_status = "elevated"
        elif len(alerts) > 0:
            system_status = "alert"

        # Build a readable system brief
        venue_names = [v.name for v in venues[:5]]
        alert_summary = (
            f"{len(alerts)} active alert(s): {critical_count} Critical, {high_count} High"
            if alerts else "No active alerts — all systems nominal."
        )

        return {
            "system_status": system_status,
            "total_venues": len(venues),
            "total_crowd_estimate": round(total_crowd, 0),
            "active_alerts": len(alerts),
            "critical_alerts": critical_count,
            "high_alerts": high_count,
            "alert_summary": alert_summary,
            "monitored_venues": venue_names,
            "intelligence_engine": {
                "status": "online",
                "model": LaminarIntelligenceService._cached_model or "rule-based",
                "llm_online": LaminarIntelligenceService._ollama_online,
            },
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }


# ─── Singleton ────────────────────────────────────────────────────────────────

laminar_intelligence = LaminarIntelligenceService()
