"""add emailverification fields

Revision ID: 10b8270bc67e
Revises: e5540ab7d462
Create Date: 2026-03-01 02:41:15.042852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10b8270bc67e'
down_revision: Union[str, Sequence[str], None] = 'e5540ab7d462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 1️⃣ Add column with temporary server default
    op.add_column(
        'users',
        sa.Column(
            'is_verified',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )
    )

    # 2️⃣ Add remaining columns
    op.add_column(
        'users',
        sa.Column('verification_token', sa.String(length=255), nullable=True)
    )

    op.add_column(
        'users',
        sa.Column('verification_token_expires_at',
                  sa.DateTime(timezone=True), nullable=True)
    )

    # 3️⃣ Create indexes
    op.create_index(op.f('ix_users_is_verified'), 'users',
                    ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_verification_token'),
                    'users', ['verification_token'], unique=True)

    # 4️⃣ Remove server default (clean design)
    op.alter_column('users', 'is_verified', server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_column('users', 'verification_token_expires_at')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
