"""Add UserVenueAccess and update UserRole

Revision ID: 32e82872f709
Revises: 3cb30dcf5396
Create Date: 2026-04-17 10:54:15.217204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e82872f709'
down_revision: Union[str, Sequence[str], None] = '3cb30dcf5396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_venue_access',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'venue_id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_venue_access_user_id'), 'user_venue_access', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_venue_access_venue_id'), 'user_venue_access', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_venue_access_venue_id'), table_name='user_venue_access')
    op.drop_index(op.f('ix_user_venue_access_user_id'), table_name='user_venue_access')
    op.drop_table('user_venue_access')
    # ### end Alembic commands ###
