"""Add email alerts

Revision ID: 3cb30dcf5396
Revises: 7c6d3f7b1c51
Create Date: 2026-03-23 23:06:28.460403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cb30dcf5396'
down_revision: Union[str, Sequence[str], None] = '7c6d3f7b1c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cameras', 'last_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('users', sa.Column('alert_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('receive_email_alerts', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('venues', 'warning_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('700'))
    op.alter_column('venues', 'critical_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('900'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'critical_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('900'))
    op.alter_column('venues', 'warning_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('700'))
    op.drop_column('users', 'receive_email_alerts')
    op.drop_column('users', 'alert_email')
    op.alter_column('cameras', 'last_snapshot',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
