"""fresh_inital_schema

Revision ID: 45c0c2717c0e
Revises: 
Create Date: 2026-02-28 18:57:18.966772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c0c2717c0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('venues',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('warning_threshold_percent', sa.Integer(), nullable=False),
    sa.Column('critical_threshold_percent', sa.Integer(), nullable=False),
    sa.Column('dynamic_risk_score', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_under_maintenance', sa.Boolean(), nullable=False),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('prediction_enabled', sa.Boolean(), nullable=False),
    sa.Column('anomaly_detection_enabled', sa.Boolean(), nullable=False),
    sa.Column('model_metadata', sa.JSON(), nullable=True),
    sa.Column('last_prediction_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_context', sa.JSON(), nullable=True),
    sa.Column('updated_context', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search_vector', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_venue_active_city', 'venues', ['is_active', 'city'], unique=False)
    op.create_index('ix_venue_risk_score', 'venues', ['dynamic_risk_score'], unique=False)
    op.create_index(op.f('ix_venues_city'), 'venues', ['city'], unique=False)
    op.create_index(op.f('ix_venues_code'), 'venues', ['code'], unique=True)
    op.create_index(op.f('ix_venues_country'), 'venues', ['country'], unique=False)
    op.create_index(op.f('ix_venues_created_at'), 'venues', ['created_at'], unique=False)
    op.create_index(op.f('ix_venues_created_by'), 'venues', ['created_by'], unique=False)
    op.create_index(op.f('ix_venues_deleted_at'), 'venues', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_venues_dynamic_risk_score'), 'venues', ['dynamic_risk_score'], unique=False)
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_index(op.f('ix_venues_is_active'), 'venues', ['is_active'], unique=False)
    op.create_index(op.f('ix_venues_is_deleted'), 'venues', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_venues_last_accessed_at'), 'venues', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=False)
    op.create_index(op.f('ix_venues_search_vector'), 'venues', ['search_vector'], unique=False)
    op.create_index(op.f('ix_venues_tenant_id'), 'venues', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_venues_updated_at'), 'venues', ['updated_at'], unique=False)
    op.create_index(op.f('ix_venues_updated_by'), 'venues', ['updated_by'], unique=False)
    op.create_table('cameras',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('stream_url', sa.String(length=1000), nullable=True),
    sa.Column('stream_type', sa.String(length=50), nullable=False),
    sa.Column('health_status', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('resolution_width', sa.Integer(), nullable=True),
    sa.Column('resolution_height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('hardware_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('last_frame_at', sa.DateTime(), nullable=True),
    sa.Column('detection_enabled', sa.Boolean(), nullable=False),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('model_config', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_context', sa.JSON(), nullable=True),
    sa.Column('updated_context', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search_vector', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_camera_active_online', 'cameras', ['is_active', 'is_online'], unique=False)
    op.create_index('ix_camera_heartbeat', 'cameras', [sa.literal_column('last_heartbeat_at DESC')], unique=False)
    op.create_index('ix_camera_model_version', 'cameras', ['model_version'], unique=False)
    op.create_index('ix_camera_venue_active', 'cameras', ['venue_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_cameras_code'), 'cameras', ['code'], unique=True)
    op.create_index(op.f('ix_cameras_created_at'), 'cameras', ['created_at'], unique=False)
    op.create_index(op.f('ix_cameras_created_by'), 'cameras', ['created_by'], unique=False)
    op.create_index(op.f('ix_cameras_deleted_at'), 'cameras', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cameras_health_status'), 'cameras', ['health_status'], unique=False)
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_index(op.f('ix_cameras_is_active'), 'cameras', ['is_active'], unique=False)
    op.create_index(op.f('ix_cameras_is_deleted'), 'cameras', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_cameras_is_online'), 'cameras', ['is_online'], unique=False)
    op.create_index(op.f('ix_cameras_last_accessed_at'), 'cameras', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_cameras_model_version'), 'cameras', ['model_version'], unique=False)
    op.create_index(op.f('ix_cameras_name'), 'cameras', ['name'], unique=False)
    op.create_index(op.f('ix_cameras_search_vector'), 'cameras', ['search_vector'], unique=False)
    op.create_index(op.f('ix_cameras_stream_type'), 'cameras', ['stream_type'], unique=False)
    op.create_index(op.f('ix_cameras_tenant_id'), 'cameras', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cameras_updated_at'), 'cameras', ['updated_at'], unique=False)
    op.create_index(op.f('ix_cameras_updated_by'), 'cameras', ['updated_by'], unique=False)
    op.create_index(op.f('ix_cameras_venue_id'), 'cameras', ['venue_id'], unique=False)
    op.create_table('crowd_metrics',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(), nullable=False),
    sa.Column('bucket_end', sa.DateTime(), nullable=False),
    sa.Column('bucket_type', sa.String(length=20), nullable=False),
    sa.Column('avg_count', sa.Float(), nullable=False),
    sa.Column('min_count', sa.Integer(), nullable=False),
    sa.Column('max_count', sa.Integer(), nullable=False),
    sa.Column('total_samples', sa.Integer(), nullable=False),
    sa.Column('rolling_avg_5', sa.Float(), nullable=True),
    sa.Column('rolling_avg_15', sa.Float(), nullable=True),
    sa.Column('growth_rate_percent', sa.Float(), nullable=True),
    sa.Column('predicted_next', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('model_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_context', sa.JSON(), nullable=True),
    sa.Column('updated_context', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search_vector', sa.String(), nullable=True),
    sa.CheckConstraint('anomaly_score IS NULL OR (anomaly_score >= 0 AND anomaly_score <= 1)', name='check_anomaly_score_range'),
    sa.CheckConstraint('avg_count >= 0', name='check_avg_non_negative'),
    sa.CheckConstraint('bucket_end > bucket_start', name='check_bucket_end_after_start'),
    sa.CheckConstraint('max_count >= min_count', name='check_max_gte_min'),
    sa.CheckConstraint('min_count >= 0', name='check_min_count_non_negative'),
    sa.CheckConstraint('total_samples > 0', name='check_samples_positive'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_metrics_anomaly_score'), 'crowd_metrics', ['anomaly_score'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_bucket_start'), 'crowd_metrics', ['bucket_start'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_bucket_type'), 'crowd_metrics', ['bucket_type'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_created_at'), 'crowd_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_created_by'), 'crowd_metrics', ['created_by'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_deleted_at'), 'crowd_metrics', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_id'), 'crowd_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_is_deleted'), 'crowd_metrics', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_last_accessed_at'), 'crowd_metrics', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_max_count'), 'crowd_metrics', ['max_count'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_model_name'), 'crowd_metrics', ['model_name'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_predicted_next'), 'crowd_metrics', ['predicted_next'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_risk_level'), 'crowd_metrics', ['risk_level'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_search_vector'), 'crowd_metrics', ['search_vector'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_tenant_id'), 'crowd_metrics', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_updated_at'), 'crowd_metrics', ['updated_at'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_updated_by'), 'crowd_metrics', ['updated_by'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_venue_id'), 'crowd_metrics', ['venue_id'], unique=False)
    op.create_index('ix_metric_anomaly', 'crowd_metrics', [sa.literal_column('anomaly_score DESC'), sa.literal_column('bucket_start DESC')], unique=False)
    op.create_index('ix_metric_bucket_type_time', 'crowd_metrics', ['bucket_type', sa.literal_column('bucket_start DESC')], unique=False)
    op.create_index('ix_metric_risk_time', 'crowd_metrics', ['risk_level', sa.literal_column('bucket_start DESC')], unique=False)
    op.create_index('ix_metric_venue_time', 'crowd_metrics', ['venue_id', sa.literal_column('bucket_start DESC')], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('category', sa.Enum('SYSTEM', 'SECURITY', 'CAMERA', 'DETECTION', 'USER', 'MAINTENANCE', name='alertcategory'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='alertstatus'), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('acknowledgement_count', sa.Integer(), nullable=False),
    sa.Column('notification_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_assigned_to_id'), 'alerts', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_alerts_camera_id'), 'alerts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index('ix_alerts_category_created', 'alerts', ['category', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_is_deleted'), 'alerts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_severity_status', 'alerts', ['severity', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_title'), 'alerts', ['title'], unique=False)
    op.create_index('ix_alerts_venue_created', 'alerts', ['venue_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_venue_id'), 'alerts', ['venue_id'], unique=False)
    op.create_index('ix_alerts_venue_status', 'alerts', ['venue_id', 'status'], unique=False)
    op.create_table('crowd_frames',
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('frame_hash', sa.String(length=255), nullable=True),
    sa.Column('image_reference', sa.String(length=1000), nullable=True),
    sa.Column('detected_count', sa.Integer(), nullable=False),
    sa.Column('bounding_boxes', sa.JSON(), nullable=True),
    sa.Column('detection_confidence_avg', sa.Float(), nullable=True),
    sa.Column('confidence_threshold_met', sa.Boolean(), nullable=True),
    sa.Column('region_detections', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_context', sa.JSON(), nullable=True),
    sa.Column('updated_context', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search_vector', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_crowd_frames_camera_id'), 'crowd_frames', ['camera_id'], unique=False)
    op.create_index(op.f('ix_crowd_frames_captured_at'), 'crowd_frames', ['captured_at'], unique=False)
    op.create_index(op.f('ix_crowd_frames_confidence_threshold_met'), 'crowd_frames', ['confidence_threshold_met'], unique=False)
    op.create_index(op.f('ix_crowd_frames_created_at'), 'crowd_frames', ['created_at'], unique=False)
    op.create_index(op.f('ix_crowd_frames_created_by'), 'crowd_frames', ['created_by'], unique=False)
    op.create_index(op.f('ix_crowd_frames_deleted_at'), 'crowd_frames', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_crowd_frames_detected_count'), 'crowd_frames', ['detected_count'], unique=False)
    op.create_index(op.f('ix_crowd_frames_frame_hash'), 'crowd_frames', ['frame_hash'], unique=False)
    op.create_index(op.f('ix_crowd_frames_id'), 'crowd_frames', ['id'], unique=False)
    op.create_index(op.f('ix_crowd_frames_is_deleted'), 'crowd_frames', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crowd_frames_last_accessed_at'), 'crowd_frames', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_crowd_frames_model_name'), 'crowd_frames', ['model_name'], unique=False)
    op.create_index(op.f('ix_crowd_frames_model_version'), 'crowd_frames', ['model_version'], unique=False)
    op.create_index(op.f('ix_crowd_frames_search_vector'), 'crowd_frames', ['search_vector'], unique=False)
    op.create_index(op.f('ix_crowd_frames_tenant_id'), 'crowd_frames', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_crowd_frames_updated_at'), 'crowd_frames', ['updated_at'], unique=False)
    op.create_index(op.f('ix_crowd_frames_updated_by'), 'crowd_frames', ['updated_by'], unique=False)
    op.create_index('ix_frame_camera_time', 'crowd_frames', ['camera_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_index('ix_frame_confidence', 'crowd_frames', ['confidence_threshold_met'], unique=False)
    op.create_index('ix_frame_count', 'crowd_frames', [sa.literal_column('detected_count DESC')], unique=False)
    op.create_index('ix_frame_model_version', 'crowd_frames', ['model_name', 'model_version'], unique=False)
    op.create_table('detections',
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x_min', sa.Float(), nullable=False),
    sa.Column('y_min', sa.Float(), nullable=False),
    sa.Column('x_max', sa.Float(), nullable=False),
    sa.Column('y_max', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_context', sa.JSON(), nullable=True),
    sa.Column('updated_context', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search_vector', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_camera_id'), 'detections', ['camera_id'], unique=False)
    op.create_index('ix_detections_camera_time', 'detections', ['camera_id', 'detected_at'], unique=False)
    op.create_index('ix_detections_confidence', 'detections', ['confidence'], unique=False)
    op.create_index(op.f('ix_detections_created_at'), 'detections', ['created_at'], unique=False)
    op.create_index(op.f('ix_detections_created_by'), 'detections', ['created_by'], unique=False)
    op.create_index(op.f('ix_detections_deleted_at'), 'detections', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_detections_detected_at'), 'detections', ['detected_at'], unique=False)
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.create_index(op.f('ix_detections_is_deleted'), 'detections', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_detections_label'), 'detections', ['label'], unique=False)
    op.create_index('ix_detections_label_time', 'detections', ['label', 'detected_at'], unique=False)
    op.create_index(op.f('ix_detections_last_accessed_at'), 'detections', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_detections_search_vector'), 'detections', ['search_vector'], unique=False)
    op.create_index(op.f('ix_detections_tenant_id'), 'detections', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_detections_updated_at'), 'detections', ['updated_at'], unique=False)
    op.create_index(op.f('ix_detections_updated_by'), 'detections', ['updated_by'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_history_alert_changed', 'alert_history', ['alert_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_alert_history_alert_id'), 'alert_history', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_history_id'), 'alert_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_history_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_alert_id'), table_name='alert_history')
    op.drop_index('ix_alert_history_alert_changed', table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_detections_updated_by'), table_name='detections')
    op.drop_index(op.f('ix_detections_updated_at'), table_name='detections')
    op.drop_index(op.f('ix_detections_tenant_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_search_vector'), table_name='detections')
    op.drop_index(op.f('ix_detections_last_accessed_at'), table_name='detections')
    op.drop_index('ix_detections_label_time', table_name='detections')
    op.drop_index(op.f('ix_detections_label'), table_name='detections')
    op.drop_index(op.f('ix_detections_is_deleted'), table_name='detections')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_detected_at'), table_name='detections')
    op.drop_index(op.f('ix_detections_deleted_at'), table_name='detections')
    op.drop_index(op.f('ix_detections_created_by'), table_name='detections')
    op.drop_index(op.f('ix_detections_created_at'), table_name='detections')
    op.drop_index('ix_detections_confidence', table_name='detections')
    op.drop_index('ix_detections_camera_time', table_name='detections')
    op.drop_index(op.f('ix_detections_camera_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index('ix_frame_model_version', table_name='crowd_frames')
    op.drop_index('ix_frame_count', table_name='crowd_frames')
    op.drop_index('ix_frame_confidence', table_name='crowd_frames')
    op.drop_index('ix_frame_camera_time', table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_updated_by'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_updated_at'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_tenant_id'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_search_vector'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_model_version'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_model_name'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_last_accessed_at'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_is_deleted'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_id'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_frame_hash'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_detected_count'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_deleted_at'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_created_by'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_created_at'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_confidence_threshold_met'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_captured_at'), table_name='crowd_frames')
    op.drop_index(op.f('ix_crowd_frames_camera_id'), table_name='crowd_frames')
    op.drop_table('crowd_frames')
    op.drop_index('ix_alerts_venue_status', table_name='alerts')
    op.drop_index(op.f('ix_alerts_venue_id'), table_name='alerts')
    op.drop_index('ix_alerts_venue_created', table_name='alerts')
    op.drop_index(op.f('ix_alerts_title'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index('ix_alerts_severity_status', table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_deleted'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index('ix_alerts_category_created', table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_camera_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_assigned_to_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_metric_venue_time', table_name='crowd_metrics')
    op.drop_index('ix_metric_risk_time', table_name='crowd_metrics')
    op.drop_index('ix_metric_bucket_type_time', table_name='crowd_metrics')
    op.drop_index('ix_metric_anomaly', table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_venue_id'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_updated_by'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_updated_at'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_tenant_id'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_search_vector'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_risk_level'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_predicted_next'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_model_name'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_max_count'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_last_accessed_at'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_is_deleted'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_id'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_deleted_at'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_created_by'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_created_at'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_bucket_type'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_bucket_start'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_anomaly_score'), table_name='crowd_metrics')
    op.drop_table('crowd_metrics')
    op.drop_index(op.f('ix_cameras_venue_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_updated_by'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_updated_at'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_tenant_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_stream_type'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_search_vector'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_name'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_model_version'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_last_accessed_at'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_is_online'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_is_deleted'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_is_active'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_health_status'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_deleted_at'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_created_by'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_created_at'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_code'), table_name='cameras')
    op.drop_index('ix_camera_venue_active', table_name='cameras')
    op.drop_index('ix_camera_model_version', table_name='cameras')
    op.drop_index('ix_camera_heartbeat', table_name='cameras')
    op.drop_index('ix_camera_active_online', table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_venues_updated_by'), table_name='venues')
    op.drop_index(op.f('ix_venues_updated_at'), table_name='venues')
    op.drop_index(op.f('ix_venues_tenant_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_search_vector'), table_name='venues')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_index(op.f('ix_venues_last_accessed_at'), table_name='venues')
    op.drop_index(op.f('ix_venues_is_deleted'), table_name='venues')
    op.drop_index(op.f('ix_venues_is_active'), table_name='venues')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_dynamic_risk_score'), table_name='venues')
    op.drop_index(op.f('ix_venues_deleted_at'), table_name='venues')
    op.drop_index(op.f('ix_venues_created_by'), table_name='venues')
    op.drop_index(op.f('ix_venues_created_at'), table_name='venues')
    op.drop_index(op.f('ix_venues_country'), table_name='venues')
    op.drop_index(op.f('ix_venues_code'), table_name='venues')
    op.drop_index(op.f('ix_venues_city'), table_name='venues')
    op.drop_index('ix_venue_risk_score', table_name='venues')
    op.drop_index('ix_venue_active_city', table_name='venues')
    op.drop_table('venues')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
