"""camera hardening improvements

Revision ID: 58a2f79068f8
Revises: 10b8270bc67e
Create Date: 2026-03-02 20:38:27.493006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a2f79068f8'
down_revision: Union[str, Sequence[str], None] = '10b8270bc67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('location_label', sa.String(length=100), nullable=True))
    op.add_column('cameras', sa.Column('zone_name', sa.String(length=100), nullable=True))
    op.add_column('cameras', sa.Column('floor_level', sa.String(length=50), nullable=True))
    op.add_column('cameras', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('cameras', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_index('ix_camera_geo_coordinates', 'cameras', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_camera_venue_location', 'cameras', ['venue_id', 'location_label'], unique=False)
    op.create_index('ix_camera_venue_zone', 'cameras', ['venue_id', 'zone_name'], unique=False)
    op.create_index(op.f('ix_cameras_location_label'), 'cameras', ['location_label'], unique=False)
    op.create_index(op.f('ix_cameras_zone_name'), 'cameras', ['zone_name'], unique=False)
    op.drop_index(op.f('ix_detections_camera_time'), table_name='detections')
    op.create_index('ix_detections_camera_detected', 'detections', ['camera_id', 'detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detections_camera_detected', table_name='detections')
    op.create_index(op.f('ix_detections_camera_time'), 'detections', ['camera_id', 'detected_at'], unique=False)
    op.drop_index(op.f('ix_cameras_zone_name'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_location_label'), table_name='cameras')
    op.drop_index('ix_camera_venue_zone', table_name='cameras')
    op.drop_index('ix_camera_venue_location', table_name='cameras')
    op.drop_index('ix_camera_geo_coordinates', table_name='cameras')
    op.drop_column('cameras', 'longitude')
    op.drop_column('cameras', 'latitude')
    op.drop_column('cameras', 'floor_level')
    op.drop_column('cameras', 'zone_name')
    op.drop_column('cameras', 'location_label')
    # ### end Alembic commands ###
