"""add missing fields to crowd_metric

Revision ID: 664c2e9f6442
Revises: f406ea657c5c
Create Date: 2026-02-28 22:45:29.216589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '664c2e9f6442'
down_revision: Union[str, Sequence[str], None] = 'f406ea657c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cameras', 'last_heartbeat_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('crowd_metrics', sa.Column('camera_id', sa.UUID(), nullable=True))
    op.add_column('crowd_metrics', sa.Column('avg_confidence', sa.Float(), nullable=True))
    op.add_column('crowd_metrics', sa.Column('occupancy_percent', sa.Float(), nullable=True))
    op.add_column('crowd_metrics', sa.Column('density_score', sa.Float(), nullable=True))
    op.add_column('crowd_metrics', sa.Column('dynamic_risk_score', sa.Float(), nullable=True))
    op.alter_column('crowd_metrics', 'bucket_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('crowd_metrics', 'bucket_end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_crowd_metrics_camera_id'), 'crowd_metrics', ['camera_id'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_dynamic_risk_score'), 'crowd_metrics', ['dynamic_risk_score'], unique=False)
    op.create_index('ix_metric_camera_time', 'crowd_metrics', ['camera_id', sa.literal_column('bucket_start DESC')], unique=False)
    op.create_index('ix_metric_risk_score', 'crowd_metrics', [sa.literal_column('dynamic_risk_score DESC')], unique=False)
    op.create_foreign_key(None, 'crowd_metrics', 'cameras', ['camera_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crowd_metrics', type_='foreignkey')
    op.drop_index('ix_metric_risk_score', table_name='crowd_metrics')
    op.drop_index('ix_metric_camera_time', table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_dynamic_risk_score'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_camera_id'), table_name='crowd_metrics')
    op.alter_column('crowd_metrics', 'bucket_end',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('crowd_metrics', 'bucket_start',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('crowd_metrics', 'dynamic_risk_score')
    op.drop_column('crowd_metrics', 'density_score')
    op.drop_column('crowd_metrics', 'occupancy_percent')
    op.drop_column('crowd_metrics', 'avg_confidence')
    op.drop_column('crowd_metrics', 'camera_id')
    op.alter_column('cameras', 'last_heartbeat_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
