"""create crowd_alerts table

Revision ID: 79efcdde1d94
Revises: e62428613aee
Create Date: 2026-02-28 19:11:41.099843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79efcdde1d94'
down_revision: Union[str, Sequence[str], None] = 'e62428613aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crowd_alerts',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_context', sa.JSON(), nullable=True),
    sa.Column('updated_context', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search_vector', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_alert_escalation', 'crowd_alerts', ['escalation_level', 'status'], unique=False)
    op.create_index('ix_alert_status_created', 'crowd_alerts', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_alert_venue_status', 'crowd_alerts', ['venue_id', 'status'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_created_at'), 'crowd_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_created_by'), 'crowd_alerts', ['created_by'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_deleted_at'), 'crowd_alerts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_id'), 'crowd_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_is_deleted'), 'crowd_alerts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_last_accessed_at'), 'crowd_alerts', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_metric_id'), 'crowd_alerts', ['metric_id'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_risk_level'), 'crowd_alerts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_search_vector'), 'crowd_alerts', ['search_vector'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_status'), 'crowd_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_tenant_id'), 'crowd_alerts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_updated_at'), 'crowd_alerts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_updated_by'), 'crowd_alerts', ['updated_by'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_venue_id'), 'crowd_alerts', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crowd_alerts_venue_id'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_updated_by'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_updated_at'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_tenant_id'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_status'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_search_vector'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_risk_level'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_metric_id'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_last_accessed_at'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_is_deleted'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_id'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_deleted_at'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_created_by'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_created_at'), table_name='crowd_alerts')
    op.drop_index('ix_alert_venue_status', table_name='crowd_alerts')
    op.drop_index('ix_alert_status_created', table_name='crowd_alerts')
    op.drop_index('ix_alert_escalation', table_name='crowd_alerts')
    op.drop_table('crowd_alerts')
    # ### end Alembic commands ###
