"""Add language preference

Revision ID: 7c6d3f7b1c51
Revises: f07fb37244d9
Create Date: 2026-03-15 22:10:51.322953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6d3f7b1c51'
down_revision: Union[str, Sequence[str], None] = 'f07fb37244d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_preference', sa.String(length=10), server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language_preference')
    # ### end Alembic commands ###
