"""Add static image mode to cameras

Revision ID: 82b97c2410ae
Revises: 32e82872f709
Create Date: 2026-05-05 16:11:57.411416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b97c2410ae'
down_revision: Union[str, Sequence[str], None] = '32e82872f709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('static_mode_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('cameras', sa.Column('static_image_url', sa.String(length=1000), nullable=True))
    op.alter_column('person_dwell_times', 'snapshot_path',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('person_dwell_times', 'session_id')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('super_admin', 'admin', 'user', name='userrole', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('super_admin', 'admin', 'user', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.add_column('person_dwell_times', sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.alter_column('person_dwell_times', 'snapshot_path',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('cameras', 'static_image_url')
    op.drop_column('cameras', 'static_mode_enabled')
    # ### end Alembic commands ###
