"""add_user_profile_and_alert_contacts

Revision ID: 8cecee389616
Revises: a2ab814e0fdd
Create Date: 2026-03-12 20:49:27.250800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cecee389616'
down_revision: Union[str, Sequence[str], None] = 'a2ab814e0fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('receive_sms', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_alert_contacts_id'), 'alert_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_alert_contacts_phone_number'), 'alert_contacts', ['phone_number'], unique=False)
    op.create_index(op.f('ix_alert_contacts_receive_sms'), 'alert_contacts', ['receive_sms'], unique=False)
    op.create_index(op.f('ix_alert_contacts_user_id'), 'alert_contacts', ['user_id'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('receive_sms_alerts', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'receive_sms_alerts')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_alert_contacts_user_id'), table_name='alert_contacts')
    op.drop_index(op.f('ix_alert_contacts_receive_sms'), table_name='alert_contacts')
    op.drop_index(op.f('ix_alert_contacts_phone_number'), table_name='alert_contacts')
    op.drop_index(op.f('ix_alert_contacts_id'), table_name='alert_contacts')
    op.drop_table('alert_contacts')
    # ### end Alembic commands ###
