"""Add QueueEstimate table

Revision ID: a2ab814e0fdd
Revises: fde0f1442d62
Create Date: 2026-03-11 14:37:23.804017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ab814e0fdd'
down_revision: Union[str, Sequence[str], None] = 'fde0f1442d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_estimates',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('queue_length', sa.Integer(), nullable=False, comment='Total estimated number of people currently waiting in line'),
    sa.Column('service_rate', sa.Float(), nullable=False, comment='Estimated number of people processed per minute'),
    sa.Column('estimated_wait_time', sa.String(length=100), nullable=False, comment="Human readable wait time (e.g., '20 minutes')"),
    sa.Column('wait_time_minutes', sa.Integer(), nullable=True, comment='Integer wait time in minutes for analytic sorting'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_context', sa.JSON(), nullable=True),
    sa.Column('updated_context', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search_vector', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_queue_venue_time', 'queue_estimates', ['venue_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_queue_estimates_created_at'), 'queue_estimates', ['created_at'], unique=False)
    op.create_index(op.f('ix_queue_estimates_created_by'), 'queue_estimates', ['created_by'], unique=False)
    op.create_index(op.f('ix_queue_estimates_deleted_at'), 'queue_estimates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_queue_estimates_id'), 'queue_estimates', ['id'], unique=False)
    op.create_index(op.f('ix_queue_estimates_is_deleted'), 'queue_estimates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_queue_estimates_last_accessed_at'), 'queue_estimates', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_queue_estimates_search_vector'), 'queue_estimates', ['search_vector'], unique=False)
    op.create_index(op.f('ix_queue_estimates_tenant_id'), 'queue_estimates', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_queue_estimates_timestamp'), 'queue_estimates', ['timestamp'], unique=False)
    op.create_index(op.f('ix_queue_estimates_updated_at'), 'queue_estimates', ['updated_at'], unique=False)
    op.create_index(op.f('ix_queue_estimates_updated_by'), 'queue_estimates', ['updated_by'], unique=False)
    op.create_index(op.f('ix_queue_estimates_venue_id'), 'queue_estimates', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_estimates_venue_id'), table_name='queue_estimates')
    op.drop_index(op.f('ix_queue_estimates_updated_by'), table_name='queue_estimates')
    op.drop_index(op.f('ix_queue_estimates_updated_at'), table_name='queue_estimates')
    op.drop_index(op.f('ix_queue_estimates_timestamp'), table_name='queue_estimates')
    op.drop_index(op.f('ix_queue_estimates_tenant_id'), table_name='queue_estimates')
    op.drop_index(op.f('ix_queue_estimates_search_vector'), table_name='queue_estimates')
    op.drop_index(op.f('ix_queue_estimates_last_accessed_at'), table_name='queue_estimates')
    op.drop_index(op.f('ix_queue_estimates_is_deleted'), table_name='queue_estimates')
    op.drop_index(op.f('ix_queue_estimates_id'), table_name='queue_estimates')
    op.drop_index(op.f('ix_queue_estimates_deleted_at'), table_name='queue_estimates')
    op.drop_index(op.f('ix_queue_estimates_created_by'), table_name='queue_estimates')
    op.drop_index(op.f('ix_queue_estimates_created_at'), table_name='queue_estimates')
    op.drop_index('idx_queue_venue_time', table_name='queue_estimates')
    op.drop_table('queue_estimates')
    # ### end Alembic commands ###
