"""add predicition fields

Revision ID: a48beb43107d
Revises: 58a2f79068f8
Create Date: 2026-03-03 22:28:53.302540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48beb43107d'
down_revision: Union[str, Sequence[str], None] = '58a2f79068f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crowd_alerts', sa.Column('predicted_level', sa.String(length=50), nullable=True))
    op.add_column('crowd_alerts', sa.Column('predicted_risk_score', sa.Float(), nullable=True))
    op.add_column('crowd_alerts', sa.Column('escalation_probability', sa.Float(), nullable=True))
    op.add_column('crowd_alerts', sa.Column('early_warning_triggered', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_crowd_alerts_predicted_level'), 'crowd_alerts', ['predicted_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crowd_alerts_predicted_level'), table_name='crowd_alerts')
    op.drop_column('crowd_alerts', 'early_warning_triggered')
    op.drop_column('crowd_alerts', 'escalation_probability')
    op.drop_column('crowd_alerts', 'predicted_risk_score')
    op.drop_column('crowd_alerts', 'predicted_level')
    # ### end Alembic commands ###
