"""Add image_path to SOSReport

Revision ID: bbe208f6d836
Revises: 1312207d72a0
Create Date: 2026-06-01 19:41:46.025899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe208f6d836'
down_revision: Union[str, Sequence[str], None] = '1312207d72a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sos_reports', sa.Column('image_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sos_reports', 'image_path')
    # ### end Alembic commands ###
