"""Add explanation to crowd_alerts

Revision ID: bdc390f10823
Revises: a8ca675c9505
Create Date: 2026-03-10 23:43:24.844650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc390f10823'
down_revision: Union[str, Sequence[str], None] = 'a8ca675c9505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crowd_alerts', sa.Column('explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crowd_alerts', 'explanation')
    # ### end Alembic commands ###
