"""add unique contstraint and indexs to crowd_metrics

Revision ID: e5540ab7d462
Revises: 664c2e9f6442
Create Date: 2026-03-01 02:00:58.173670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5540ab7d462'
down_revision: Union[str, Sequence[str], None] = '664c2e9f6442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_metric_bucket_start', 'crowd_metrics', ['bucket_start'], unique=False)
    op.create_index('idx_metric_camera', 'crowd_metrics', ['camera_id'], unique=False)
    op.create_index('idx_metric_venue', 'crowd_metrics', ['venue_id'], unique=False)
    op.create_index('idx_metric_venue_bucket', 'crowd_metrics', ['venue_id', 'bucket_type', 'bucket_start'], unique=False)
    op.create_unique_constraint('uq_metric_camera_bucket', 'crowd_metrics', ['camera_id', 'bucket_start', 'bucket_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_metric_camera_bucket', 'crowd_metrics', type_='unique')
    op.drop_index('idx_metric_venue_bucket', table_name='crowd_metrics')
    op.drop_index('idx_metric_venue', table_name='crowd_metrics')
    op.drop_index('idx_metric_camera', table_name='crowd_metrics')
    op.drop_index('idx_metric_bucket_start', table_name='crowd_metrics')
    # ### end Alembic commands ###
