"""add_dwell_monitoring_tables

Revision ID: f07fb37244d9
Revises: 8cecee389616
Create Date: 2026-03-14 21:47:42.944907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07fb37244d9'
down_revision: Union[str, Sequence[str], None] = '8cecee389616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('zone_name', sa.String(length=120), nullable=False),
    sa.Column('polygon_coordinates', sa.JSON(), nullable=False),
    sa.Column('long_wait_threshold_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_monitoring_zones_camera_id'), 'monitoring_zones', ['camera_id'], unique=False)
    op.create_table('person_dwell_times',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=120), nullable=False),
    sa.Column('enter_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dwell_seconds', sa.Float(), nullable=False),
    sa.Column('alert_triggered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_person_dwell_times_camera_id'), 'person_dwell_times', ['camera_id'], unique=False)
    op.create_index(op.f('ix_person_dwell_times_created_at'), 'person_dwell_times', ['created_at'], unique=False)
    op.create_index(op.f('ix_person_dwell_times_tracker_id'), 'person_dwell_times', ['tracker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_dwell_times_tracker_id'), table_name='person_dwell_times')
    op.drop_index(op.f('ix_person_dwell_times_created_at'), table_name='person_dwell_times')
    op.drop_index(op.f('ix_person_dwell_times_camera_id'), table_name='person_dwell_times')
    op.drop_table('person_dwell_times')
    op.drop_index(op.f('ix_monitoring_zones_camera_id'), table_name='monitoring_zones')
    op.drop_table('monitoring_zones')
    # ### end Alembic commands ###
