"""add evidence clips

Revision ID: fde0f1442d62
Revises: bdc390f10823
Create Date: 2026-03-11 00:00:24.575212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde0f1442d62'
down_revision: Union[str, Sequence[str], None] = 'bdc390f10823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_clips',
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_context', sa.JSON(), nullable=True),
    sa.Column('updated_context', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search_vector', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_evidence_clips_camera_id'), 'evidence_clips', ['camera_id'], unique=False)
    op.create_index(op.f('ix_evidence_clips_created_at'), 'evidence_clips', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_clips_created_by'), 'evidence_clips', ['created_by'], unique=False)
    op.create_index(op.f('ix_evidence_clips_deleted_at'), 'evidence_clips', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_evidence_clips_id'), 'evidence_clips', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_clips_is_deleted'), 'evidence_clips', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_evidence_clips_last_accessed_at'), 'evidence_clips', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_evidence_clips_search_vector'), 'evidence_clips', ['search_vector'], unique=False)
    op.create_index(op.f('ix_evidence_clips_tenant_id'), 'evidence_clips', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_evidence_clips_updated_at'), 'evidence_clips', ['updated_at'], unique=False)
    op.create_index(op.f('ix_evidence_clips_updated_by'), 'evidence_clips', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_clips_updated_by'), table_name='evidence_clips')
    op.drop_index(op.f('ix_evidence_clips_updated_at'), table_name='evidence_clips')
    op.drop_index(op.f('ix_evidence_clips_tenant_id'), table_name='evidence_clips')
    op.drop_index(op.f('ix_evidence_clips_search_vector'), table_name='evidence_clips')
    op.drop_index(op.f('ix_evidence_clips_last_accessed_at'), table_name='evidence_clips')
    op.drop_index(op.f('ix_evidence_clips_is_deleted'), table_name='evidence_clips')
    op.drop_index(op.f('ix_evidence_clips_id'), table_name='evidence_clips')
    op.drop_index(op.f('ix_evidence_clips_deleted_at'), table_name='evidence_clips')
    op.drop_index(op.f('ix_evidence_clips_created_by'), table_name='evidence_clips')
    op.drop_index(op.f('ix_evidence_clips_created_at'), table_name='evidence_clips')
    op.drop_index(op.f('ix_evidence_clips_camera_id'), table_name='evidence_clips')
    op.drop_table('evidence_clips')
    # ### end Alembic commands ###
