"""Genericize CrowdAlert to SystemAlert

Revision ID: fe13ab7ff083
Revises: bbe208f6d836
Create Date: 2026-09-06 17:11:13.076627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe13ab7ff083'
down_revision: Union[str, Sequence[str], None] = 'bbe208f6d836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_alerts',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('metric_id', sa.Uuid(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_level', sa.String(length=50), nullable=True),
    sa.Column('predicted_risk_score', sa.Float(), nullable=True),
    sa.Column('escalation_probability', sa.Float(), nullable=True),
    sa.Column('early_warning_triggered', sa.Boolean(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_context', sa.JSON(), nullable=True),
    sa.Column('updated_context', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search_vector', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_system_alerts_created_at'), 'system_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_alerts_created_by'), 'system_alerts', ['created_by'], unique=False)
    op.create_index(op.f('ix_system_alerts_deleted_at'), 'system_alerts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_system_alerts_domain'), 'system_alerts', ['domain'], unique=False)
    op.create_index('ix_system_alerts_escalation', 'system_alerts', ['escalation_level', 'status'], unique=False)
    op.create_index(op.f('ix_system_alerts_id'), 'system_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_system_alerts_is_deleted'), 'system_alerts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_system_alerts_last_accessed_at'), 'system_alerts', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_system_alerts_metric_id'), 'system_alerts', ['metric_id'], unique=False)
    op.create_index(op.f('ix_system_alerts_predicted_level'), 'system_alerts', ['predicted_level'], unique=False)
    op.create_index(op.f('ix_system_alerts_risk_level'), 'system_alerts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_system_alerts_search_vector'), 'system_alerts', ['search_vector'], unique=False)
    op.create_index(op.f('ix_system_alerts_status'), 'system_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_system_alerts_tenant_id'), 'system_alerts', ['tenant_id'], unique=False)
    op.create_index('ix_system_alerts_timeline', 'system_alerts', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_system_alerts_updated_at'), 'system_alerts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_system_alerts_updated_by'), 'system_alerts', ['updated_by'], unique=False)
    op.create_index(op.f('ix_system_alerts_venue_id'), 'system_alerts', ['venue_id'], unique=False)
    op.create_index('ix_system_alerts_venue_status', 'system_alerts', ['venue_id', 'status'], unique=False)
    op.drop_index(op.f('ix_alert_escalation'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_alert_timeline'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_alert_venue_status'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_created_at'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_created_by'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_deleted_at'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_id'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_is_deleted'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_last_accessed_at'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_metric_id'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_predicted_level'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_risk_level'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_search_vector'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_status'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_tenant_id'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_updated_at'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_updated_by'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_venue_id'), table_name='crowd_alerts')
    op.drop_table('crowd_alerts')
    op.alter_column('cameras', 'camera_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'generic'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cameras', 'camera_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'generic'::character varying"))
    op.create_table('crowd_alerts',
    sa.Column('venue_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('escalation_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_notified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_accessed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_vector', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('predicted_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('predicted_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('escalation_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('early_warning_triggered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('crowd_alerts_venue_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('crowd_alerts_pkey'))
    )
    op.create_index(op.f('ix_crowd_alerts_venue_id'), 'crowd_alerts', ['venue_id'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_updated_by'), 'crowd_alerts', ['updated_by'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_updated_at'), 'crowd_alerts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_tenant_id'), 'crowd_alerts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_status'), 'crowd_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_search_vector'), 'crowd_alerts', ['search_vector'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_risk_level'), 'crowd_alerts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_predicted_level'), 'crowd_alerts', ['predicted_level'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_metric_id'), 'crowd_alerts', ['metric_id'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_last_accessed_at'), 'crowd_alerts', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_is_deleted'), 'crowd_alerts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_id'), 'crowd_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_deleted_at'), 'crowd_alerts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_created_by'), 'crowd_alerts', ['created_by'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_created_at'), 'crowd_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_venue_status'), 'crowd_alerts', ['venue_id', 'status'], unique=False)
    op.create_index(op.f('ix_alert_timeline'), 'crowd_alerts', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_alert_escalation'), 'crowd_alerts', ['escalation_level', 'status'], unique=False)
    op.drop_index('ix_system_alerts_venue_status', table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_venue_id'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_updated_by'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_updated_at'), table_name='system_alerts')
    op.drop_index('ix_system_alerts_timeline', table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_tenant_id'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_status'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_search_vector'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_risk_level'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_predicted_level'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_metric_id'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_last_accessed_at'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_is_deleted'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_id'), table_name='system_alerts')
    op.drop_index('ix_system_alerts_escalation', table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_domain'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_deleted_at'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_created_by'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_created_at'), table_name='system_alerts')
    op.drop_table('system_alerts')
    # ### end Alembic commands ###
